### ISSUE TITLE
Consider UDP Support

### ISSUE THREAD

**Issue by NoahO** [MisterTea/EternalTCP#23]
Love the idea, Mosh is really unusable for me because of the no scrollback. 

However, one of the great things about Mosh for me is the UDP support. 

Certain countries (read between the lines..) rate limit / throttle SSH traffic because it is useful for firewall evasion.. To the point where if I do a certain amount of traffic over SSH to a box, *all* packets on any protocol to that IP get delayed in a kind of backoff algorithm. 

Mosh was great, because the UDP traffic really isn't counted by a stateful firewall, and there's no session to send reset packets to... so it really flew under the radar and made my life a lot easier. 

I definitely see the advantage of only supporting TCP, but would it be possible to get an option for both?

**Comment by MisterTea** [comment]
ET only uses ssh to initialize the connection. After that it uses a custom
protocol that runs on a separate port. Do you really need UDP or is it
sufficient to simply not be on the same port/protocol as ssh?

**Comment by NoahO** [comment]
If it is encrypted TCP then it will be flow limited by some countries. It's an open TCP session so they can write a rule like "Any session open for a long time that isn't whitelisted should be limited"

If it's encrypted UDP then it's hard for them to count it as a "session" without storing a lot of state in memory. So to write a similar rule they'd have to correlate UDP packets over time..

**Comment by MisterTea** [comment]
That's true in theory, but note that adding UDP support would be
significant work. If ET isn't being throttled at the moment, I would rather
not have to support UDP until it's absolutely needed.

On Wed, Apr 5, 2017 at 8:06 PM NoahO <notifications@github.com> wrote:

If it is encrypted TCP then it will be flow limited by some countries. It's
an open TCP session so they can write a rule like "Any session open for a
long time that isn't whitelisted should be limited"

If it's encrypted UDP then it's hard for them to count it as a "session"
without storing a lot of state in memory. So to write a similar rule they'd
have to correlate UDP packets over time..

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/MisterTea/EternalTCP/issues/23#issuecomment-292056484>,
or mute the thread

**Comment by NoahO** [comment]
> That's true in theory, but note that adding UDP support would be significant work.

I agree, and at this stage probably not relevant to a whole lot of people. But I thought better to know about it at an (earlier) stage than a later stage. I don't expect you to do anything about it but better I say something now than later.. 

> If ET isn't being throttled at the moment, I would rather not have to support UDP until it's absolutely needed.

This I can't really comment on. Different regions have different policies. But it's not unreasonable to assume that some are a white-list approach and random encrypted TCP traffic (such as ET) is already being rate throttled.

**Comment by MisterTea** [comment]
Also note that if a company is going so far as to detect ET packets, they
would be able to do this for udp as well. You can't encrypt the packet
header

**Comment by divinity76** [comment]
when you say that SSH traffic is throttled, is it the Great Firewall of China that you're talking about?

**Comment by MisterTea** [comment]
I'm going to close this since it's speculation whether TCP is actually a problem for anyone.  Feel free to make another issue if it turns out we need UDP.

**Comment by wheelerlaw** [comment]
UDP support would make using very latent connections much more responsive. That is the nice thing about mosh is that it works over connections that have very high latency. But it lacks any sort of scrollback so it is difficult to use unless you use a terminal multiplexer on the server side, which means the addition of an another tool to the setup.
