### ISSUE TITLE
Implement local echo (a la mosh)

### ISSUE THREAD

**Issue by andreimarcu** [MisterTea/EternalTCP#40]
Not sure how doable this is, but it would reduce the feature gap with mosh quite a lot!

**Comment by MisterTea** [comment]
I could do some naive thing such as drawing a letter when someone inputs it, then backing up when the next byte comes in.  The issue is that I don't know how portable this is.  Because mosh is itself a terminal emulator, it knows exactly what/where it drew in a predictive way so it can revert it correctly every time.  If we had deep integration with a terminal emulator such as hyper.js or iTerm, then they could do the input prediction at their layer with more accuracy.

Either way, I'll try it and let's see what breaks.

**Comment by MisterTea** [comment]
I tried to implement this but it's a total nightmare without having control of the terminal emulator.  This would be a good feature to add to hyper.js or some terminal emulator, but it doesn't belong at this layer.
